### ISSUE TITLE
don't barf on /favicon.ico

### ISSUE THREAD

**Issue by leifj** [its-dirg/SATOSA#3]
When pointing a browser at the proxy saml backend metadata (from docker image) I get this:

```
2016-04-22 09:51:13,719 [108] [ERROR] Unknown error
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/satosa/base.py", line 273, in run
    spec = self.module_router.endpoint_routing(context)
  File "/usr/local/lib/python3.4/dist-packages/satosa/routing.py", line 155, in endpoint_routing
    for regex, spec in self.backends[backend]["endpoints"]:
KeyError: 'favicon.ico'
```

Very likely this is a non-fatal error but it should be avoided. Serve up a simple favicon or return a 404 - whatever makes most browsers happy.

**Comment by rebeckag** [comment]
Closed by be6934b.
