### ISSUE TITLE
missing entityID in metadata yields "unknown error"

### ISSUE THREAD

**Issue by leifj** [its-dirg/SATOSA#7]
```
2016-04-27 08:22:32,604 [5611] [ERROR] Unknown error
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/satosa/base.py", line 274, in run
    resp = self._run_bound_endpoint(context, spec)
  File "/usr/local/lib/python3.4/dist-packages/satosa/base.py", line 202, in _run_bound_endpoint
    return spec[0](context, *spec[1:])
  File "/usr/local/lib/python3.4/dist-packages/satosa/frontends/saml2.py", line 70, in handle_authn_request
    return self._handle_authn_request(context, binding_in, self.idp)
  File "/usr/local/lib/python3.4/dist-packages/satosa/frontends/saml2.py", line 225, in _handle_authn_request
    context.state)
  File "/usr/local/lib/python3.4/dist-packages/satosa/frontends/saml2.py", line 171, in extract_request
    entity_id=_authn_req.issuer.text, request=_authn_req)
  File "/usr/local/lib/python3.4/dist-packages/saml2/entity.py", line 283, in pick_binding
    srvs = sfunc(entity_id, binding, descr_type)
  File "/usr/local/lib/python3.4/dist-packages/saml2/mdstore.py", line 1063, in assertion_consumer_service
    "assertion_consumer_service", binding)
  File "/usr/local/lib/python3.4/dist-packages/saml2/mdstore.py", line 952, in service
    raise UnknownSystemEntity(entity_id)
saml2.s_utils.UnknownSystemEntity: https://dev.play.sunet.se
```

This could definitely be improved upon :-)

**Comment by rebeckag** [comment]
It sure could, thanks for reporting it!
Would it suffice to handle the UnknownSystemEntity and produce a better log message?
I can't think of any way of gracefully handling it, since it will be hard to find the corresponding metadata (which is missing the entityID).

**Comment by leifj** [comment]
Skickat från min iPhone

> 27 apr. 2016 kl. 12:27 skrev Rebecka Gulliksson <notifications@github.com>:
> 
> It sure could, thanks for reporting it!
> Would it suffice to handle the UnknownSystemEntity and produce a better log message?
> 

Yeah i think so
